// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pack.proto

package msgpack

import (
	payload "example.com/lite_demo/test/payload"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgPack struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Type   []byte                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Target string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MsgPack_Emoji
	//	*MsgPack_Blocks
	//	*MsgPack_TankChange
	//	*MsgPack_Request
	//	*MsgPack_Hit
	//	*MsgPack_Operate
	//	*MsgPack_Shot
	//	*MsgPack_Notice
	Payload       isMsgPack_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPack) Reset() {
	*x = MsgPack{}
	mi := &file_pack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPack) ProtoMessage() {}

func (x *MsgPack) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPack.ProtoReflect.Descriptor instead.
func (*MsgPack) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{0}
}

func (x *MsgPack) GetType() []byte {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *MsgPack) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MsgPack) GetPayload() isMsgPack_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MsgPack) GetEmoji() *payload.Emojipayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgPack_Emoji); ok {
			return x.Emoji
		}
	}
	return nil
}

func (x *MsgPack) GetBlocks() *payload.Blockspayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgPack_Blocks); ok {
			return x.Blocks
		}
	}
	return nil
}

func (x *MsgPack) GetTankChange() *payload.TankChangePayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgPack_TankChange); ok {
			return x.TankChange
		}
	}
	return nil
}

func (x *MsgPack) GetRequest() *payload.RequestPayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgPack_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *MsgPack) GetHit() *payload.HitPayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgPack_Hit); ok {
			return x.Hit
		}
	}
	return nil
}

func (x *MsgPack) GetOperate() *payload.OperatePayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgPack_Operate); ok {
			return x.Operate
		}
	}
	return nil
}

func (x *MsgPack) GetShot() *payload.ShotPayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgPack_Shot); ok {
			return x.Shot
		}
	}
	return nil
}

func (x *MsgPack) GetNotice() string {
	if x != nil {
		if x, ok := x.Payload.(*MsgPack_Notice); ok {
			return x.Notice
		}
	}
	return ""
}

type isMsgPack_Payload interface {
	isMsgPack_Payload()
}

type MsgPack_Emoji struct {
	Emoji *payload.Emojipayload `protobuf:"bytes,3,opt,name=emoji,proto3,oneof"`
}

type MsgPack_Blocks struct {
	Blocks *payload.Blockspayload `protobuf:"bytes,4,opt,name=blocks,proto3,oneof"`
}

type MsgPack_TankChange struct {
	TankChange *payload.TankChangePayload `protobuf:"bytes,5,opt,name=tankChange,proto3,oneof"`
}

type MsgPack_Request struct {
	Request *payload.RequestPayload `protobuf:"bytes,6,opt,name=request,proto3,oneof"`
}

type MsgPack_Hit struct {
	Hit *payload.HitPayload `protobuf:"bytes,7,opt,name=hit,proto3,oneof"`
}

type MsgPack_Operate struct {
	Operate *payload.OperatePayload `protobuf:"bytes,8,opt,name=operate,proto3,oneof"`
}

type MsgPack_Shot struct {
	Shot *payload.ShotPayload `protobuf:"bytes,9,opt,name=shot,proto3,oneof"`
}

type MsgPack_Notice struct {
	Notice string `protobuf:"bytes,10,opt,name=notice,proto3,oneof"`
}

func (*MsgPack_Emoji) isMsgPack_Payload() {}

func (*MsgPack_Blocks) isMsgPack_Payload() {}

func (*MsgPack_TankChange) isMsgPack_Payload() {}

func (*MsgPack_Request) isMsgPack_Payload() {}

func (*MsgPack_Hit) isMsgPack_Payload() {}

func (*MsgPack_Operate) isMsgPack_Payload() {}

func (*MsgPack_Shot) isMsgPack_Payload() {}

func (*MsgPack_Notice) isMsgPack_Payload() {}

var File_pack_proto protoreflect.FileDescriptor

const file_pack_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pack.proto\x12\amsgpack\x1a\x15payload/payload.proto\"\xb8\x03\n" +
	"\aMsgPack\x12\x12\n" +
	"\x04type\x18\x01 \x01(\fR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12-\n" +
	"\x05emoji\x18\x03 \x01(\v2\x15.payload.emojipayloadH\x00R\x05emoji\x120\n" +
	"\x06blocks\x18\x04 \x01(\v2\x16.payload.blockspayloadH\x00R\x06blocks\x12<\n" +
	"\n" +
	"tankChange\x18\x05 \x01(\v2\x1a.payload.tankChangePayloadH\x00R\n" +
	"tankChange\x123\n" +
	"\arequest\x18\x06 \x01(\v2\x17.payload.requestPayloadH\x00R\arequest\x12'\n" +
	"\x03hit\x18\a \x01(\v2\x13.payload.hitPayloadH\x00R\x03hit\x123\n" +
	"\aoperate\x18\b \x01(\v2\x17.payload.operatePayloadH\x00R\aoperate\x12*\n" +
	"\x04shot\x18\t \x01(\v2\x14.payload.shotPayloadH\x00R\x04shot\x12\x18\n" +
	"\x06notice\x18\n" +
	" \x01(\tH\x00R\x06noticeB\t\n" +
	"\apayloadB$Z\"example.com/lite_demo/test;msgpackb\x06proto3"

var (
	file_pack_proto_rawDescOnce sync.Once
	file_pack_proto_rawDescData []byte
)

func file_pack_proto_rawDescGZIP() []byte {
	file_pack_proto_rawDescOnce.Do(func() {
		file_pack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pack_proto_rawDesc), len(file_pack_proto_rawDesc)))
	})
	return file_pack_proto_rawDescData
}

var file_pack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pack_proto_goTypes = []any{
	(*MsgPack)(nil),                   // 0: msgpack.MsgPack
	(*payload.Emojipayload)(nil),      // 1: payload.emojipayload
	(*payload.Blockspayload)(nil),     // 2: payload.blockspayload
	(*payload.TankChangePayload)(nil), // 3: payload.tankChangePayload
	(*payload.RequestPayload)(nil),    // 4: payload.requestPayload
	(*payload.HitPayload)(nil),        // 5: payload.hitPayload
	(*payload.OperatePayload)(nil),    // 6: payload.operatePayload
	(*payload.ShotPayload)(nil),       // 7: payload.shotPayload
}
var file_pack_proto_depIdxs = []int32{
	1, // 0: msgpack.MsgPack.emoji:type_name -> payload.emojipayload
	2, // 1: msgpack.MsgPack.blocks:type_name -> payload.blockspayload
	3, // 2: msgpack.MsgPack.tankChange:type_name -> payload.tankChangePayload
	4, // 3: msgpack.MsgPack.request:type_name -> payload.requestPayload
	5, // 4: msgpack.MsgPack.hit:type_name -> payload.hitPayload
	6, // 5: msgpack.MsgPack.operate:type_name -> payload.operatePayload
	7, // 6: msgpack.MsgPack.shot:type_name -> payload.shotPayload
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pack_proto_init() }
func file_pack_proto_init() {
	if File_pack_proto != nil {
		return
	}
	file_pack_proto_msgTypes[0].OneofWrappers = []any{
		(*MsgPack_Emoji)(nil),
		(*MsgPack_Blocks)(nil),
		(*MsgPack_TankChange)(nil),
		(*MsgPack_Request)(nil),
		(*MsgPack_Hit)(nil),
		(*MsgPack_Operate)(nil),
		(*MsgPack_Shot)(nil),
		(*MsgPack_Notice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pack_proto_rawDesc), len(file_pack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pack_proto_goTypes,
		DependencyIndexes: file_pack_proto_depIdxs,
		MessageInfos:      file_pack_proto_msgTypes,
	}.Build()
	File_pack_proto = out.File
	file_pack_proto_goTypes = nil
	file_pack_proto_depIdxs = nil
}
