# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datastruct/datastruct.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'datastruct/datastruct.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64\x61tastruct/datastruct.proto\x12\ndatastruct\" \n\x08mappoint\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"K\n\x05\x62lock\x12\x1f\n\x01p\x18\x01 \x03(\x0b\x32\x14.datastruct.mappoint\x12\t\n\x01l\x18\x02 \x01(\x05\x12\t\n\x01w\x18\x03 \x01(\x05\x12\x0b\n\x03\x64ir\x18\x04 \x01(\x0c\"\x96\x01\n\x04tank\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12\x0e\n\x06reload\x18\x03 \x01(\r\x12\x0f\n\x07trigger\x18\x04 \x01(\x08\x12\x11\n\tGunFacing\x18\x05 \x01(\x0c\x12\x0e\n\x06status\x18\x06 \x01(\x0c\x12\x13\n\x0borientation\x18\x07 \x01(\x0c\x12\x10\n\x08username\x18\x08 \x01(\t\x12\r\n\x05point\x18\t \x01(\x05\x42\x32Z0example.com/lite_demo/test/datastruct;datastructb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datastruct.datastruct_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0example.com/lite_demo/test/datastruct;datastruct'
  _globals['_MAPPOINT']._serialized_start=43
  _globals['_MAPPOINT']._serialized_end=75
  _globals['_BLOCK']._serialized_start=77
  _globals['_BLOCK']._serialized_end=152
  _globals['_TANK']._serialized_start=155
  _globals['_TANK']._serialized_end=305
# @@protoc_insertion_point(module_scope)
