// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: datastruct/datastruct.proto

package datastruct

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mappoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mappoint) Reset() {
	*x = Mappoint{}
	mi := &file_datastruct_datastruct_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mappoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mappoint) ProtoMessage() {}

func (x *Mappoint) ProtoReflect() protoreflect.Message {
	mi := &file_datastruct_datastruct_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mappoint.ProtoReflect.Descriptor instead.
func (*Mappoint) Descriptor() ([]byte, []int) {
	return file_datastruct_datastruct_proto_rawDescGZIP(), []int{0}
}

func (x *Mappoint) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Mappoint) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P             []*Mappoint            `protobuf:"bytes,1,rep,name=p,proto3" json:"p,omitempty"`
	L             int32                  `protobuf:"varint,2,opt,name=l,proto3" json:"l,omitempty"`
	W             int32                  `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	Dir           []byte                 `protobuf:"bytes,4,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_datastruct_datastruct_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_datastruct_datastruct_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_datastruct_datastruct_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetP() []*Mappoint {
	if x != nil {
		return x.P
	}
	return nil
}

func (x *Block) GetL() int32 {
	if x != nil {
		return x.L
	}
	return 0
}

func (x *Block) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Block) GetDir() []byte {
	if x != nil {
		return x.Dir
	}
	return nil
}

type Tank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             uint32                 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Reload        uint32                 `protobuf:"varint,3,opt,name=reload,proto3" json:"reload,omitempty"`
	Trigger       bool                   `protobuf:"varint,4,opt,name=trigger,proto3" json:"trigger,omitempty"`
	GunFacing     []byte                 `protobuf:"bytes,5,opt,name=GunFacing,proto3" json:"GunFacing,omitempty"`
	Status        []byte                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Orientation   []byte                 `protobuf:"bytes,7,opt,name=orientation,proto3" json:"orientation,omitempty"`
	Username      string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`
	Point         int32                  `protobuf:"varint,9,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tank) Reset() {
	*x = Tank{}
	mi := &file_datastruct_datastruct_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tank) ProtoMessage() {}

func (x *Tank) ProtoReflect() protoreflect.Message {
	mi := &file_datastruct_datastruct_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tank.ProtoReflect.Descriptor instead.
func (*Tank) Descriptor() ([]byte, []int) {
	return file_datastruct_datastruct_proto_rawDescGZIP(), []int{2}
}

func (x *Tank) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Tank) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Tank) GetReload() uint32 {
	if x != nil {
		return x.Reload
	}
	return 0
}

func (x *Tank) GetTrigger() bool {
	if x != nil {
		return x.Trigger
	}
	return false
}

func (x *Tank) GetGunFacing() []byte {
	if x != nil {
		return x.GunFacing
	}
	return nil
}

func (x *Tank) GetStatus() []byte {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Tank) GetOrientation() []byte {
	if x != nil {
		return x.Orientation
	}
	return nil
}

func (x *Tank) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Tank) GetPoint() int32 {
	if x != nil {
		return x.Point
	}
	return 0
}

var File_datastruct_datastruct_proto protoreflect.FileDescriptor

const file_datastruct_datastruct_proto_rawDesc = "" +
	"\n" +
	"\x1bdatastruct/datastruct.proto\x12\n" +
	"datastruct\"&\n" +
	"\bmappoint\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"Y\n" +
	"\x05block\x12\"\n" +
	"\x01p\x18\x01 \x03(\v2\x14.datastruct.mappointR\x01p\x12\f\n" +
	"\x01l\x18\x02 \x01(\x05R\x01l\x12\f\n" +
	"\x01w\x18\x03 \x01(\x05R\x01w\x12\x10\n" +
	"\x03dir\x18\x04 \x01(\fR\x03dir\"\xde\x01\n" +
	"\x04tank\x12\f\n" +
	"\x01x\x18\x01 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\rR\x01y\x12\x16\n" +
	"\x06reload\x18\x03 \x01(\rR\x06reload\x12\x18\n" +
	"\atrigger\x18\x04 \x01(\bR\atrigger\x12\x1c\n" +
	"\tGunFacing\x18\x05 \x01(\fR\tGunFacing\x12\x16\n" +
	"\x06status\x18\x06 \x01(\fR\x06status\x12 \n" +
	"\vorientation\x18\a \x01(\fR\vorientation\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\x12\x14\n" +
	"\x05point\x18\t \x01(\x05R\x05pointB2Z0example.com/lite_demo/test/datastruct;datastructb\x06proto3"

var (
	file_datastruct_datastruct_proto_rawDescOnce sync.Once
	file_datastruct_datastruct_proto_rawDescData []byte
)

func file_datastruct_datastruct_proto_rawDescGZIP() []byte {
	file_datastruct_datastruct_proto_rawDescOnce.Do(func() {
		file_datastruct_datastruct_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_datastruct_datastruct_proto_rawDesc), len(file_datastruct_datastruct_proto_rawDesc)))
	})
	return file_datastruct_datastruct_proto_rawDescData
}

var file_datastruct_datastruct_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_datastruct_datastruct_proto_goTypes = []any{
	(*Mappoint)(nil), // 0: datastruct.mappoint
	(*Block)(nil),    // 1: datastruct.block
	(*Tank)(nil),     // 2: datastruct.tank
}
var file_datastruct_datastruct_proto_depIdxs = []int32{
	0, // 0: datastruct.block.p:type_name -> datastruct.mappoint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_datastruct_datastruct_proto_init() }
func file_datastruct_datastruct_proto_init() {
	if File_datastruct_datastruct_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_datastruct_datastruct_proto_rawDesc), len(file_datastruct_datastruct_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_datastruct_datastruct_proto_goTypes,
		DependencyIndexes: file_datastruct_datastruct_proto_depIdxs,
		MessageInfos:      file_datastruct_datastruct_proto_msgTypes,
	}.Build()
	File_datastruct_datastruct_proto = out.File
	file_datastruct_datastruct_proto_goTypes = nil
	file_datastruct_datastruct_proto_depIdxs = nil
}
