// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: payload/payload.proto

package payload

import (
	datastruct "example.com/lite_demo/test/datastruct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Emojipayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Emoji         []byte                 `protobuf:"bytes,2,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emojipayload) Reset() {
	*x = Emojipayload{}
	mi := &file_payload_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emojipayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emojipayload) ProtoMessage() {}

func (x *Emojipayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emojipayload.ProtoReflect.Descriptor instead.
func (*Emojipayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{0}
}

func (x *Emojipayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Emojipayload) GetEmoji() []byte {
	if x != nil {
		return x.Emoji
	}
	return nil
}

type Blockspayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P             []*datastruct.Block    `protobuf:"bytes,1,rep,name=p,proto3" json:"p,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blockspayload) Reset() {
	*x = Blockspayload{}
	mi := &file_payload_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blockspayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blockspayload) ProtoMessage() {}

func (x *Blockspayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blockspayload.ProtoReflect.Descriptor instead.
func (*Blockspayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{1}
}

func (x *Blockspayload) GetP() []*datastruct.Block {
	if x != nil {
		return x.P
	}
	return nil
}

type TankChangePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	TurnTo        bool                   `protobuf:"varint,2,opt,name=turnTo,proto3" json:"turnTo,omitempty"`
	X             uint32                 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TankChangePayload) Reset() {
	*x = TankChangePayload{}
	mi := &file_payload_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TankChangePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TankChangePayload) ProtoMessage() {}

func (x *TankChangePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TankChangePayload.ProtoReflect.Descriptor instead.
func (*TankChangePayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{2}
}

func (x *TankChangePayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TankChangePayload) GetTurnTo() bool {
	if x != nil {
		return x.TurnTo
	}
	return false
}

func (x *TankChangePayload) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TankChangePayload) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type RequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPayload) Reset() {
	*x = RequestPayload{}
	mi := &file_payload_payload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPayload) ProtoMessage() {}

func (x *RequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPayload.ProtoReflect.Descriptor instead.
func (*RequestPayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{3}
}

func (x *RequestPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RequestPayload) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HitPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Victim        string                 `protobuf:"bytes,2,opt,name=victim,proto3" json:"victim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitPayload) Reset() {
	*x = HitPayload{}
	mi := &file_payload_payload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitPayload) ProtoMessage() {}

func (x *HitPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitPayload.ProtoReflect.Descriptor instead.
func (*HitPayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{4}
}

func (x *HitPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *HitPayload) GetVictim() string {
	if x != nil {
		return x.Victim
	}
	return ""
}

type OperatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Up            bool                   `protobuf:"varint,1,opt,name=up,proto3" json:"up,omitempty"`
	Down          bool                   `protobuf:"varint,2,opt,name=down,proto3" json:"down,omitempty"`
	Left          bool                   `protobuf:"varint,3,opt,name=left,proto3" json:"left,omitempty"`
	Right         bool                   `protobuf:"varint,4,opt,name=right,proto3" json:"right,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatePayload) Reset() {
	*x = OperatePayload{}
	mi := &file_payload_payload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatePayload) ProtoMessage() {}

func (x *OperatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatePayload.ProtoReflect.Descriptor instead.
func (*OperatePayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{5}
}

func (x *OperatePayload) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *OperatePayload) GetDown() bool {
	if x != nil {
		return x.Down
	}
	return false
}

func (x *OperatePayload) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

func (x *OperatePayload) GetRight() bool {
	if x != nil {
		return x.Right
	}
	return false
}

func (x *OperatePayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ShotPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	X             uint32                 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Facing        []byte                 `protobuf:"bytes,4,opt,name=Facing,proto3" json:"Facing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShotPayload) Reset() {
	*x = ShotPayload{}
	mi := &file_payload_payload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotPayload) ProtoMessage() {}

func (x *ShotPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotPayload.ProtoReflect.Descriptor instead.
func (*ShotPayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{6}
}

func (x *ShotPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ShotPayload) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ShotPayload) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ShotPayload) GetFacing() []byte {
	if x != nil {
		return x.Facing
	}
	return nil
}

var File_payload_payload_proto protoreflect.FileDescriptor

const file_payload_payload_proto_rawDesc = "" +
	"\n" +
	"\x15payload/payload.proto\x12\apayload\x1a\x1bdatastruct/datastruct.proto\"@\n" +
	"\femojipayload\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05emoji\x18\x02 \x01(\fR\x05emoji\"0\n" +
	"\rblockspayload\x12\x1f\n" +
	"\x01p\x18\x01 \x03(\v2\x11.datastruct.blockR\x01p\"c\n" +
	"\x11tankChangePayload\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06turnTo\x18\x02 \x01(\bR\x06turnTo\x12\f\n" +
	"\x01x\x18\x03 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\rR\x01y\"F\n" +
	"\x0erequestPayload\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"@\n" +
	"\n" +
	"hitPayload\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06victim\x18\x02 \x01(\tR\x06victim\"v\n" +
	"\x0eoperatePayload\x12\x0e\n" +
	"\x02up\x18\x01 \x01(\bR\x02up\x12\x12\n" +
	"\x04down\x18\x02 \x01(\bR\x04down\x12\x12\n" +
	"\x04left\x18\x03 \x01(\bR\x04left\x12\x14\n" +
	"\x05right\x18\x04 \x01(\bR\x05right\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\"]\n" +
	"\vshotPayload\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\f\n" +
	"\x01x\x18\x02 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\rR\x01y\x12\x16\n" +
	"\x06Facing\x18\x04 \x01(\fR\x06FacingB,Z*example.com/lite_demo/test/payload;payloadb\x06proto3"

var (
	file_payload_payload_proto_rawDescOnce sync.Once
	file_payload_payload_proto_rawDescData []byte
)

func file_payload_payload_proto_rawDescGZIP() []byte {
	file_payload_payload_proto_rawDescOnce.Do(func() {
		file_payload_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_payload_proto_rawDesc), len(file_payload_payload_proto_rawDesc)))
	})
	return file_payload_payload_proto_rawDescData
}

var file_payload_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_payload_payload_proto_goTypes = []any{
	(*Emojipayload)(nil),      // 0: payload.emojipayload
	(*Blockspayload)(nil),     // 1: payload.blockspayload
	(*TankChangePayload)(nil), // 2: payload.tankChangePayload
	(*RequestPayload)(nil),    // 3: payload.requestPayload
	(*HitPayload)(nil),        // 4: payload.hitPayload
	(*OperatePayload)(nil),    // 5: payload.operatePayload
	(*ShotPayload)(nil),       // 6: payload.shotPayload
	(*datastruct.Block)(nil),  // 7: datastruct.block
}
var file_payload_payload_proto_depIdxs = []int32{
	7, // 0: payload.blockspayload.p:type_name -> datastruct.block
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payload_payload_proto_init() }
func file_payload_payload_proto_init() {
	if File_payload_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_payload_proto_rawDesc), len(file_payload_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_payload_proto_goTypes,
		DependencyIndexes: file_payload_payload_proto_depIdxs,
		MessageInfos:      file_payload_payload_proto_msgTypes,
	}.Build()
	File_payload_payload_proto = out.File
	file_payload_payload_proto_goTypes = nil
	file_payload_payload_proto_depIdxs = nil
}
