// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: payload/payload.proto

package payload

import (
	datastruct "example.com/lite_demo/test/datastruct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Emojipayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Emoji         []byte                 `protobuf:"bytes,2,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emojipayload) Reset() {
	*x = Emojipayload{}
	mi := &file_payload_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emojipayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emojipayload) ProtoMessage() {}

func (x *Emojipayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emojipayload.ProtoReflect.Descriptor instead.
func (*Emojipayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{0}
}

func (x *Emojipayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Emojipayload) GetEmoji() []byte {
	if x != nil {
		return x.Emoji
	}
	return nil
}

type Blockspayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blockpoints   []*datastruct.Block    `protobuf:"bytes,1,rep,name=blockpoints,proto3" json:"blockpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blockspayload) Reset() {
	*x = Blockspayload{}
	mi := &file_payload_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blockspayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blockspayload) ProtoMessage() {}

func (x *Blockspayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blockspayload.ProtoReflect.Descriptor instead.
func (*Blockspayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{1}
}

func (x *Blockspayload) GetBlockpoints() []*datastruct.Block {
	if x != nil {
		return x.Blockpoints
	}
	return nil
}

type GameConfigPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapSizeX      uint32                 `protobuf:"varint,1,opt,name=mapSizeX,proto3" json:"mapSizeX,omitempty"`
	MapSizeY      uint32                 `protobuf:"varint,2,opt,name=mapSizeY,proto3" json:"mapSizeY,omitempty"`
	Map           *Blockspayload         `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	TickInterval  int32                  `protobuf:"varint,4,opt,name=tickInterval,proto3" json:"tickInterval,omitempty"`
	MapRenderMS   int32                  `protobuf:"varint,5,opt,name=mapRenderMS,proto3" json:"mapRenderMS,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Tanks         []*datastruct.Tank     `protobuf:"bytes,7,rep,name=tanks,proto3" json:"tanks,omitempty"`
	TankSizeX     int32                  `protobuf:"varint,8,opt,name=tankSizeX,proto3" json:"tankSizeX,omitempty"`
	TankSizeY     int32                  `protobuf:"varint,9,opt,name=tankSizeY,proto3" json:"tankSizeY,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameConfigPayload) Reset() {
	*x = GameConfigPayload{}
	mi := &file_payload_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameConfigPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameConfigPayload) ProtoMessage() {}

func (x *GameConfigPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameConfigPayload.ProtoReflect.Descriptor instead.
func (*GameConfigPayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{2}
}

func (x *GameConfigPayload) GetMapSizeX() uint32 {
	if x != nil {
		return x.MapSizeX
	}
	return 0
}

func (x *GameConfigPayload) GetMapSizeY() uint32 {
	if x != nil {
		return x.MapSizeY
	}
	return 0
}

func (x *GameConfigPayload) GetMap() *Blockspayload {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *GameConfigPayload) GetTickInterval() int32 {
	if x != nil {
		return x.TickInterval
	}
	return 0
}

func (x *GameConfigPayload) GetMapRenderMS() int32 {
	if x != nil {
		return x.MapRenderMS
	}
	return 0
}

func (x *GameConfigPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GameConfigPayload) GetTanks() []*datastruct.Tank {
	if x != nil {
		return x.Tanks
	}
	return nil
}

func (x *GameConfigPayload) GetTankSizeX() int32 {
	if x != nil {
		return x.TankSizeX
	}
	return 0
}

func (x *GameConfigPayload) GetTankSizeY() int32 {
	if x != nil {
		return x.TankSizeY
	}
	return 0
}

type TankChangePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	TurnTo        bool                   `protobuf:"varint,2,opt,name=turnTo,proto3" json:"turnTo,omitempty"`
	X             uint32                 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TankChangePayload) Reset() {
	*x = TankChangePayload{}
	mi := &file_payload_payload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TankChangePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TankChangePayload) ProtoMessage() {}

func (x *TankChangePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TankChangePayload.ProtoReflect.Descriptor instead.
func (*TankChangePayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{3}
}

func (x *TankChangePayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TankChangePayload) GetTurnTo() bool {
	if x != nil {
		return x.TurnTo
	}
	return false
}

func (x *TankChangePayload) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TankChangePayload) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type GameStatusPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tanks         []*datastruct.Tank     `protobuf:"bytes,1,rep,name=tanks,proto3" json:"tanks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStatusPayload) Reset() {
	*x = GameStatusPayload{}
	mi := &file_payload_payload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStatusPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatusPayload) ProtoMessage() {}

func (x *GameStatusPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatusPayload.ProtoReflect.Descriptor instead.
func (*GameStatusPayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{4}
}

func (x *GameStatusPayload) GetTanks() []*datastruct.Tank {
	if x != nil {
		return x.Tanks
	}
	return nil
}

type RequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPayload) Reset() {
	*x = RequestPayload{}
	mi := &file_payload_payload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPayload) ProtoMessage() {}

func (x *RequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPayload.ProtoReflect.Descriptor instead.
func (*RequestPayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{5}
}

func (x *RequestPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RequestPayload) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HitPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Victim        string                 `protobuf:"bytes,2,opt,name=victim,proto3" json:"victim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitPayload) Reset() {
	*x = HitPayload{}
	mi := &file_payload_payload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitPayload) ProtoMessage() {}

func (x *HitPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitPayload.ProtoReflect.Descriptor instead.
func (*HitPayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{6}
}

func (x *HitPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *HitPayload) GetVictim() string {
	if x != nil {
		return x.Victim
	}
	return ""
}

type OperatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Up            bool                   `protobuf:"varint,1,opt,name=up,proto3" json:"up,omitempty"`
	Down          bool                   `protobuf:"varint,2,opt,name=down,proto3" json:"down,omitempty"`
	Left          bool                   `protobuf:"varint,3,opt,name=left,proto3" json:"left,omitempty"`
	Right         bool                   `protobuf:"varint,4,opt,name=right,proto3" json:"right,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatePayload) Reset() {
	*x = OperatePayload{}
	mi := &file_payload_payload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatePayload) ProtoMessage() {}

func (x *OperatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatePayload.ProtoReflect.Descriptor instead.
func (*OperatePayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{7}
}

func (x *OperatePayload) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *OperatePayload) GetDown() bool {
	if x != nil {
		return x.Down
	}
	return false
}

func (x *OperatePayload) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

func (x *OperatePayload) GetRight() bool {
	if x != nil {
		return x.Right
	}
	return false
}

func (x *OperatePayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type ShotPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	X             uint32                 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Facing        []byte                 `protobuf:"bytes,4,opt,name=Facing,proto3" json:"Facing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShotPayload) Reset() {
	*x = ShotPayload{}
	mi := &file_payload_payload_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShotPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShotPayload) ProtoMessage() {}

func (x *ShotPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShotPayload.ProtoReflect.Descriptor instead.
func (*ShotPayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{8}
}

func (x *ShotPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ShotPayload) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ShotPayload) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ShotPayload) GetFacing() []byte {
	if x != nil {
		return x.Facing
	}
	return nil
}

var File_payload_payload_proto protoreflect.FileDescriptor

const file_payload_payload_proto_rawDesc = "" +
	"\n" +
	"\x15payload/payload.proto\x12\apayload\x1a\x1bdatastruct/datastruct.proto\"@\n" +
	"\femojipayload\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05emoji\x18\x02 \x01(\fR\x05emoji\"D\n" +
	"\rblockspayload\x123\n" +
	"\vblockpoints\x18\x01 \x03(\v2\x11.datastruct.blockR\vblockpoints\"\xbb\x02\n" +
	"\x11gameConfigPayload\x12\x1a\n" +
	"\bmapSizeX\x18\x01 \x01(\rR\bmapSizeX\x12\x1a\n" +
	"\bmapSizeY\x18\x02 \x01(\rR\bmapSizeY\x12(\n" +
	"\x03map\x18\x03 \x01(\v2\x16.payload.blockspayloadR\x03map\x12\"\n" +
	"\ftickInterval\x18\x04 \x01(\x05R\ftickInterval\x12 \n" +
	"\vmapRenderMS\x18\x05 \x01(\x05R\vmapRenderMS\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12&\n" +
	"\x05tanks\x18\a \x03(\v2\x10.datastruct.tankR\x05tanks\x12\x1c\n" +
	"\ttankSizeX\x18\b \x01(\x05R\ttankSizeX\x12\x1c\n" +
	"\ttankSizeY\x18\t \x01(\x05R\ttankSizeY\"c\n" +
	"\x11tankChangePayload\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06turnTo\x18\x02 \x01(\bR\x06turnTo\x12\f\n" +
	"\x01x\x18\x03 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\rR\x01y\";\n" +
	"\x11gameStatusPayload\x12&\n" +
	"\x05tanks\x18\x01 \x03(\v2\x10.datastruct.tankR\x05tanks\"F\n" +
	"\x0erequestPayload\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"@\n" +
	"\n" +
	"hitPayload\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06victim\x18\x02 \x01(\tR\x06victim\"v\n" +
	"\x0eoperatePayload\x12\x0e\n" +
	"\x02up\x18\x01 \x01(\bR\x02up\x12\x12\n" +
	"\x04down\x18\x02 \x01(\bR\x04down\x12\x12\n" +
	"\x04left\x18\x03 \x01(\bR\x04left\x12\x14\n" +
	"\x05right\x18\x04 \x01(\bR\x05right\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\"]\n" +
	"\vshotPayload\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\f\n" +
	"\x01x\x18\x02 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\rR\x01y\x12\x16\n" +
	"\x06Facing\x18\x04 \x01(\fR\x06FacingB,Z*example.com/lite_demo/test/payload;payloadb\x06proto3"

var (
	file_payload_payload_proto_rawDescOnce sync.Once
	file_payload_payload_proto_rawDescData []byte
)

func file_payload_payload_proto_rawDescGZIP() []byte {
	file_payload_payload_proto_rawDescOnce.Do(func() {
		file_payload_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_payload_proto_rawDesc), len(file_payload_payload_proto_rawDesc)))
	})
	return file_payload_payload_proto_rawDescData
}

var file_payload_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_payload_payload_proto_goTypes = []any{
	(*Emojipayload)(nil),      // 0: payload.emojipayload
	(*Blockspayload)(nil),     // 1: payload.blockspayload
	(*GameConfigPayload)(nil), // 2: payload.gameConfigPayload
	(*TankChangePayload)(nil), // 3: payload.tankChangePayload
	(*GameStatusPayload)(nil), // 4: payload.gameStatusPayload
	(*RequestPayload)(nil),    // 5: payload.requestPayload
	(*HitPayload)(nil),        // 6: payload.hitPayload
	(*OperatePayload)(nil),    // 7: payload.operatePayload
	(*ShotPayload)(nil),       // 8: payload.shotPayload
	(*datastruct.Block)(nil),  // 9: datastruct.block
	(*datastruct.Tank)(nil),   // 10: datastruct.tank
}
var file_payload_payload_proto_depIdxs = []int32{
	9,  // 0: payload.blockspayload.blockpoints:type_name -> datastruct.block
	1,  // 1: payload.gameConfigPayload.map:type_name -> payload.blockspayload
	10, // 2: payload.gameConfigPayload.tanks:type_name -> datastruct.tank
	10, // 3: payload.gameStatusPayload.tanks:type_name -> datastruct.tank
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_payload_payload_proto_init() }
func file_payload_payload_proto_init() {
	if File_payload_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_payload_proto_rawDesc), len(file_payload_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_payload_proto_goTypes,
		DependencyIndexes: file_payload_payload_proto_depIdxs,
		MessageInfos:      file_payload_payload_proto_msgTypes,
	}.Build()
	File_payload_payload_proto = out.File
	file_payload_payload_proto_goTypes = nil
	file_payload_payload_proto_depIdxs = nil
}
