syntax = "proto3";

package payload;

option go_package = "example.com/lite_demo/test/payload;payload";
// 修改为从根目录开始的相对路径
import "datastruct/datastruct.proto";

message emojipayload{
    string username = 1;
    bytes emoji = 2;
}

message blockspayload{
    repeated datastruct.block blockpoints=1;
}

message  gameConfigPayload{
    uint32 mapSizeX=1;
    uint32 mapSizeY=2;
    blockspayload map=3;
    int32 tickInterval=4;
    int32 mapRenderMS=5;
    string username=6;
    repeated datastruct.tank tanks=7;
    int32 tankSizeX=8;
    int32 tankSizeY=9;
}

message tankChangePayload{
    string username =1;
    bool turnTo=2;
    uint32 x=3;
    uint32 y=4;
}

message gameStatusPayload{
    repeated datastruct.tank tanks=1;
}

message requestPayload{
    string username =1;
    bool success=2;
}

message hitPayload{
    string username =1;
    string victim   =2;
}

message operatePayload{
    bool up=1;
    bool down=2;
    bool left=3;
    bool right=4;
    string action=5;
}

message shotPayload{
    string username =1;
    uint32 x=2;
    uint32 y=3;
    bytes Facing=4;
}