# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payload/payload.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payload/payload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from datastruct import datastruct_pb2 as datastruct_dot_datastruct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payload/payload.proto\x12\x07payload\x1a\x1b\x64\x61tastruct/datastruct.proto\"/\n\x0c\x65mojipayload\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65moji\x18\x02 \x01(\x0c\"7\n\rblockspayload\x12&\n\x0b\x62lockpoints\x18\x01 \x03(\x0b\x32\x11.datastruct.block\"\xe0\x01\n\x11gameConfigPayload\x12\x10\n\x08mapSizeX\x18\x01 \x01(\r\x12\x10\n\x08mapSizeY\x18\x02 \x01(\r\x12#\n\x03map\x18\x03 \x01(\x0b\x32\x16.payload.blockspayload\x12\x14\n\x0ctickInterval\x18\x04 \x01(\x05\x12\x13\n\x0bmapRenderMS\x18\x05 \x01(\x05\x12\x10\n\x08username\x18\x06 \x01(\t\x12\x1f\n\x05tanks\x18\x07 \x03(\x0b\x32\x10.datastruct.tank\x12\x11\n\ttankSizeX\x18\x08 \x01(\x05\x12\x11\n\ttankSizeY\x18\t \x01(\x05\"K\n\x11tankChangePayload\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06turnTo\x18\x02 \x01(\x08\x12\t\n\x01x\x18\x03 \x01(\r\x12\t\n\x01y\x18\x04 \x01(\r\"4\n\x11gameStatusPayload\x12\x1f\n\x05tanks\x18\x01 \x03(\x0b\x32\x10.datastruct.tank\"3\n\x0erequestPayload\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\".\n\nhitPayload\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0e\n\x06victim\x18\x02 \x01(\t\"W\n\x0eoperatePayload\x12\n\n\x02up\x18\x01 \x01(\x08\x12\x0c\n\x04\x64own\x18\x02 \x01(\x08\x12\x0c\n\x04left\x18\x03 \x01(\x08\x12\r\n\x05right\x18\x04 \x01(\x08\x12\x0e\n\x06\x61\x63tion\x18\x05 \x01(\t\"E\n\x0bshotPayload\x12\x10\n\x08username\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\r\x12\t\n\x01y\x18\x03 \x01(\r\x12\x0e\n\x06\x46\x61\x63ing\x18\x04 \x01(\x0c\x42,Z*example.com/lite_demo/test/payload;payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload.payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*example.com/lite_demo/test/payload;payload'
  _globals['_EMOJIPAYLOAD']._serialized_start=63
  _globals['_EMOJIPAYLOAD']._serialized_end=110
  _globals['_BLOCKSPAYLOAD']._serialized_start=112
  _globals['_BLOCKSPAYLOAD']._serialized_end=167
  _globals['_GAMECONFIGPAYLOAD']._serialized_start=170
  _globals['_GAMECONFIGPAYLOAD']._serialized_end=394
  _globals['_TANKCHANGEPAYLOAD']._serialized_start=396
  _globals['_TANKCHANGEPAYLOAD']._serialized_end=471
  _globals['_GAMESTATUSPAYLOAD']._serialized_start=473
  _globals['_GAMESTATUSPAYLOAD']._serialized_end=525
  _globals['_REQUESTPAYLOAD']._serialized_start=527
  _globals['_REQUESTPAYLOAD']._serialized_end=578
  _globals['_HITPAYLOAD']._serialized_start=580
  _globals['_HITPAYLOAD']._serialized_end=626
  _globals['_OPERATEPAYLOAD']._serialized_start=628
  _globals['_OPERATEPAYLOAD']._serialized_end=715
  _globals['_SHOTPAYLOAD']._serialized_start=717
  _globals['_SHOTPAYLOAD']._serialized_end=786
# @@protoc_insertion_point(module_scope)
