# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pack.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pack.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from payload import payload_pb2 as payload_dot_payload__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npack.proto\x12\x07msgpack\x1a\x15payload/payload.proto\"\xa4\x03\n\x07MsgPack\x12\x0c\n\x04type\x18\x01 \x01(\x0c\x12\x0e\n\x06target\x18\x02 \x01(\t\x12&\n\x05\x65moji\x18\x03 \x01(\x0b\x32\x15.payload.emojipayloadH\x00\x12\x30\n\ntankChange\x18\x05 \x01(\x0b\x32\x1a.payload.tankChangePayloadH\x00\x12*\n\x07request\x18\x06 \x01(\x0b\x32\x17.payload.requestPayloadH\x00\x12\"\n\x03hit\x18\x07 \x01(\x0b\x32\x13.payload.hitPayloadH\x00\x12*\n\x07operate\x18\x08 \x01(\x0b\x32\x17.payload.operatePayloadH\x00\x12$\n\x04shot\x18\t \x01(\x0b\x32\x14.payload.shotPayloadH\x00\x12\x10\n\x06notice\x18\n \x01(\tH\x00\x12\x30\n\ngameConfig\x18\x0b \x01(\x0b\x32\x1a.payload.gameConfigPayloadH\x00\x12\x30\n\ngameStatus\x18\x0c \x01(\x0b\x32\x1a.payload.gameStatusPayloadH\x00\x42\t\n\x07payloadB$Z\"example.com/lite_demo/test;msgpackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pack_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\"example.com/lite_demo/test;msgpack'
  _globals['_MSGPACK']._serialized_start=47
  _globals['_MSGPACK']._serialized_end=467
# @@protoc_insertion_point(module_scope)
